title: Website
tabs:
  pages:
    label: Website
    icon: page
    columns:
      - width: 2/3
        sections:
          websites:
            type: pages
            layout: cards
            size: tiny
            template: website
            status: listed
            image: page.cover
      - width: 1/3
        sections:
          drafts:
            type: pages
            template: website
            status: draft
      - width: 1/1
        sections:
          meta:
            type: pages
            parent: site.find("meta")
            create: default
  meta: tabs/meta